use std::collections::{BTreeMap, BTreeSet};
use std::io::{Read, Write};

const MAX_CHARS: usize = 4;
const MAX_RANK: u64 = 56008;

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let data = load_cached(
        "common_words.txt",
        "https://raw.githubusercontent.com/liuxilu/Proofread-Modern-Chinese-Common-Lexicon/master/%E7%8E%B0%E4%BB%A3%E6%B1%89%E8%AF%AD%E5%B8%B8%E7%94%A8%E8%AF%8D%E8%A1%A8.txt",
        false,
    )?;

    struct Entry { word: String, pinyin: String, rank: u64 }

    let mut entries: Vec<Entry> = Vec::new();
    for line in data.lines() {
        let line = line.trim();
        if line.is_empty() { continue; }
        let parts: Vec<&str> = line.split('\t').collect();
        if parts.len() < 3 { continue; }
        let word = parts[0].to_string();
        let pinyin = parts[1].to_string();
        let rank: u64 = parts[2].parse().unwrap_or(99999);
        if !word.is_empty() && word.chars().all(|c| is_cjk(c)) {
            entries.push(Entry { word, pinyin, rank });
        }
    }
    eprintln!("Loaded {} entries from 现代汉语常用词表", entries.len());

    struct CodeInfo {
        words: BTreeSet<String>,
        best_rank: u64,
        best_word: String,
        best_pinyin: String,
        char_len: usize,
    }

    let mut sp_map: BTreeMap<String, CodeInfo> = BTreeMap::new();
    let mut total = 0usize;
    let mut too_long = 0usize;
    let mut too_rare = 0usize;
    let mut sp_fail = 0usize;
    let mut sp_ok = 0usize;

    for entry in &entries {
        let n = entry.word.chars().count();
        total += 1;
        if n > MAX_CHARS { too_long += 1; continue; }
        if entry.rank > MAX_RANK { too_rare += 1; continue; }

        match word_to_shuangpin(&entry.pinyin, n) {
            Some(code) => {
                sp_ok += 1;
                let info = sp_map.entry(code).or_insert_with(|| CodeInfo {
                    words: BTreeSet::new(),
                    best_rank: u64::MAX,
                    best_word: String::new(),
                    best_pinyin: String::new(),
                    char_len: n,
                });
                info.words.insert(entry.word.clone());
                if entry.rank < info.best_rank {
                    info.best_rank = entry.rank;
                    info.best_word = entry.word.clone();
                    info.best_pinyin = entry.pinyin.replace('\'', " ");
                }
                info.char_len = info.char_len.min(n);
            }
            None => { sp_fail += 1; }
        }
    }

    let unique = sp_map.len();
    let valid = total - too_long - too_rare;
    let collapsed = sp_ok.saturating_sub(unique);
    let eff = 7776f64.log2();
    let bits = (unique as f64).log2();

    let mut by_len: BTreeMap<usize, usize> = BTreeMap::new();
    for code in sp_map.keys() {
        *by_len.entry(code.len() / 2).or_default() += 1;
    }

    println!("=== Passtale Wordlist Generator ===");
    println!("Source: 现代汉语常用词表 (proofread 2025)\n");
    println!("Total: {total}  Too long: {too_long}  Valid: {valid}");
    println!("SP fail: {sp_fail}  SP OK: {sp_ok}");
    println!("Unique codes: {unique}  Homophones collapsed: {collapsed}");
    println!("\nBy word length:");
    for (&chars, &count) in &by_len {
        println!("  {chars}-char ({} keys): {count:>6}", chars * 2);
    }
    println!("\nEntropy: {bits:.3} bits/word (log2 {unique})");
    println!("5 SP words = {:.1} bits ~ {:.1} EFF words", 5.0 * bits, 5.0 * bits / eff);

    // --- Outputs ---
    let out = std::path::PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("..");
    let mut sorted: Vec<_> = sp_map.iter().collect();
    sorted.sort_by_key(|(_, info)| info.best_rank);

    // wordlist.txt
    let path = out.join("wordlist.txt");
    let mut f = std::fs::File::create(&path)?;
    for (code, info) in &sorted {
        let others: Vec<_> = info.words.iter().filter(|w| w.as_str() != info.best_word).take(4).map(|s| s.as_str()).collect();
        let mut ex = vec![info.best_word.as_str()];
        ex.extend(others);
        writeln!(f, "{}\t{}\t{}", info.best_rank, code, ex.join("\t"))?;
    }
    eprintln!("\n{} -> {unique} entries", path.display());

    // shuangpin.wordlist (xkcdpass-compatible)
    let path = out.join("shuangpin.wordlist");
    let mut f = std::fs::File::create(&path)?;
    for (_, info) in &sorted {
        writeln!(f, "{}", info.best_word)?;
    }
    eprintln!("{}", path.display());

    // web/wordlist.js
    let web_dir = out.join("web");
    std::fs::create_dir_all(&web_dir)?;
    let path = web_dir.join("wordlist.js");
    let mut f = std::fs::File::create(&path)?;
    writeln!(f, "// Generated by passtale-wordlist-gen")?;
    writeln!(f, "// {unique} entries from 现代汉语常用词表")?;
    writeln!(f, "// [shuangpin, word, pinyin, rank, homophones...]")?;
    writeln!(f, "const WORDLIST = [")?;
    for (code, info) in &sorted {
        let homophones: Vec<_> = info.words.iter()
            .filter(|w| w.as_str() != info.best_word)
            .take(5)
            .map(|s| format!("\"{}\"", s))
            .collect();
        writeln!(f, "[\"{code}\",\"{}\",\"{}\",{},{}],",
            info.best_word, info.best_pinyin, info.best_rank,
            if homophones.is_empty() { "".into() } else { homophones.join(",") }
        )?;
    }
    writeln!(f, "];")?;
    eprintln!("{}", path.display());

    // sankey.html
    let path = out.join("sankey.html");
    let html = format!(r##"<!DOCTYPE html>
<html><head><meta charset="UTF-8"><title>Passtale Pipeline</title>
<script src="https://www.gstatic.com/charts/loader.js"></script>
<style>body{{font-family:system-ui;padding:24px;background:#fafafa}}h1{{font-size:1.4rem}}.sub{{color:#666;font-size:.9rem;margin-bottom:16px}}#c{{background:#fff;border:1px solid #e0e0e0;border-radius:8px;padding:16px}}</style>
</head><body><h1>Passtale Pipeline</h1>
<p class="sub">现代汉语常用词表 → Xiaohe Shuangpin — max_chars={MAX_CHARS}, max_rank={MAX_RANK}</p>
<div id="c"></div><script>
google.charts.load('current',{{'packages':['sankey']}});
google.charts.setOnLoadCallback(function(){{var d=new google.visualization.DataTable();
d.addColumn('string','From');d.addColumn('string','To');d.addColumn('number','W');
d.addRows([["常用词表 ({total})","Too long ({too_long})",{tl}],["常用词表 ({total})","Valid ({valid})",{valid}],
["Valid ({valid})","SP fail ({sp_fail})",{sf}],["Valid ({valid})","SP OK ({sp_ok})",{sp_ok}],
["SP OK ({sp_ok})","Unique codes ({unique})",{unique}],["SP OK ({sp_ok})","Homophones ({collapsed})",{col}]]);
new google.visualization.Sankey(document.getElementById('c')).draw(d,{{width:1000,height:400,
sankey:{{node:{{label:{{fontSize:13,bold:true}},nodePadding:24}},link:{{colorMode:'gradient'}}}}}});}});
</script></body></html>"##,
        total=total, too_long=too_long, tl=too_long.max(1), valid=valid,
        sp_fail=sp_fail, sf=sp_fail.max(1), sp_ok=sp_ok,
        unique=unique, collapsed=collapsed, col=collapsed.max(1),
        MAX_CHARS=MAX_CHARS, MAX_RANK=MAX_RANK);
    std::fs::write(&path, html)?;
    eprintln!("{}", path.display());

    Ok(())
}

fn load_cached(cache: &str, url: &str, _gzipped: bool) -> Result<String, Box<dyn std::error::Error>> {
    if std::path::Path::new(cache).exists() {
        eprintln!("Using cached {cache}");
        return Ok(std::fs::read_to_string(cache)?);
    }
    eprintln!("Downloading {url}...");
    let resp = ureq::get(url).call()?;
    let mut text = String::new();
    resp.into_reader().read_to_string(&mut text)?;
    std::fs::write(cache, &text)?;
    eprintln!("Cached -> {cache}");
    Ok(text)
}

fn is_cjk(c: char) -> bool {
    matches!(c as u32, 0x4E00..=0x9FFF | 0x3400..=0x4DBF | 0xF900..=0xFAFF)
}

fn word_to_shuangpin(pinyin: &str, char_count: usize) -> Option<String> {
    let syls: Vec<&str> = pinyin.split(|c: char| c.is_whitespace() || c == '\'').collect();
    if syls.len() != char_count { return None; }
    let mut code = String::with_capacity(char_count * 2);
    for syl in syls { let [a, b] = to_xiaohe(syl)?; code.push(a); code.push(b); }
    Some(code)
}

fn to_xiaohe(raw: &str) -> Option<[char; 2]> {
    let low = raw.to_lowercase();
    let trimmed = low.trim_end_matches(|c: char| c.is_ascii_digit());
    let s = trimmed.replace("u:", "v").replace('\u{fc}', "v");

    let (ik, ri) = if s.starts_with("zh") { ('v', 2) }
        else if s.starts_with("ch") { ('i', 2) }
        else if s.starts_with("sh") { ('u', 2) }
        else {
            let c = *s.as_bytes().first()? as char;
            if "bpmfdtnlgkhjqxrzcsyw".contains(c) && s.len() > 1 { (c, 1) }
            else if "aoev".contains(c) { ('\0', 0) }
            else { return None; }
        };

    let rest = &s[ri..];
    if rest.is_empty() { return None; }

    let fin: &str = match ik {
        'w' => match rest {
            "u"|"a"|"o"|"ai"|"ei"|"an"|"en"|"ang"|"eng" => rest,
            _ => return None,
        },
        _ => rest,
    };

    let fk = match fin {
        "a"=>'a',"o"|"uo"=>'o',"e"=>'e',"i"=>'i',"u"=>'u',"v"=>'v',
        "ai"=>'d',"ei"=>'w',"ao"=>'c',"ou"=>'z',"an"=>'j',"en"=>'f',
        "ang"=>'h',"eng"=>'g',"ong"|"iong"=>'s',"er"=>'r',"ia"|"ua"=>'x',
        "ie"=>'p',"iao"=>'n',"iu"=>'q',"ian"=>'m',"in"=>'b',
        "iang"|"uang"=>'l',"ing"=>'k',"uai"=>'k',"ui"=>'v',
        "uan"|"van"=>'r',"un"|"vn"=>'y',"ue"|"ve"=>'t', _ => return None,
    };

    let k1 = if ik == '\0' { s.as_bytes()[0] as char } else { ik };
    Some([k1, fk])
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn basic() {
        assert_eq!(to_xiaohe("zhao4"), Some(['v','c']));
        assert_eq!(to_xiaohe("lao3"), Some(['l','c']));
        assert_eq!(to_xiaohe("shi1"), Some(['u','i']));
        assert_eq!(word_to_shuangpin("lao3'shi1", 2), Some("lcui".into()));
    }

    #[test]
    fn multi_char() {
        assert_eq!(word_to_shuangpin("ban4'gong1'shi4", 3), Some("bjgsui".into()));
        assert_eq!(word_to_shuangpin("bu4'ke3'si1'yi4", 4), Some("bukesiyi".into()));
    }

    #[test]
    fn no_tone() {
        assert_eq!(to_xiaohe("de"), Some(['d','e']));
    }
}
